#!/bin/bash
apt-get update
puppet resource package git ensure=present
puppet resource package apache2 ensure=present
pupper resource package apache2 ensure=running
puppet resource file /tmp/clone ensure=absent force=true
puppet resource file /tmp/clone ensure=directory
cd /tmp/clone
git clone https://github.com/Fritdz/POC_REPO
cp -p /tmp/clone/POC_REPO/6719053N_index.html /var/www/html
