#!/bin/bash
apt-get update
puppet resource package git ensure=present
puppet resource package apache2 ensure=present
pupper resource package apache2 ensure=running
puppet resource file /tmp/6719053N/work ensure=absent force=true
puppet resource file /tmp/6719053N/work ensure=directory
cd /tmp/6719053N/work
git clone https://github.com/Fritdz/POC_REPO
cp -p /tmp/6719053N/work/POC_REPO/6719053N_index.html /var/www/html
